CS50WEB/pset1/wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = 'encyclopedia'
urlpatterns = [
    path("", views.index, name="index"),
    path("random_page", views.random_page, name="random_page"),
    path("search", views.search_page, name="search"),
    path("create", views.create_page, name="create"),
    path("update", views.update_page, name="update"),
    path("<str:title>", views.get_entry, name="entry")
]

CS50WEB/pset1/wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include("encyclopedia.urls"))
]

CS50WEB/pset1/wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

CS50WEB/pset1/wiki/encyclopedia/views.py
import random

from django import forms
from django.forms import TextInput
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from rest_framework import status

from . import util, matcher


class NewPage ( forms.Form ):
    title = forms.CharField ( label="Title",
                              strip=True,
                              widget=TextInput ( attrs={
                                  "class": "form-control"
                              } ) )
    content = forms.CharField ( label="",
                                required=True,
                                widget=forms.Textarea ( attrs={
                                    "placeholder": "Write your page markdown",
                                    "class": "form-control",
                                } )
                                )

    def set_default_value(self, title, content):
        self.fields['title'].widget = TextInput ( attrs={
            "class": "form-control",
            "value": title
        } )
        self.fields['content'].initial = content


def index(request):
    return render ( request, "encyclopedia/index.html", {
        "entries": util.list_entries ()
    } )


def get_entry(request, title):
    file = util.get_entry ( title )
    # if no file return error page
    if not file:
        return render ( request, "encyclopedia/error.html", {
            "status": status.HTTP_404_NOT_FOUND,
            "error_msg": f'Oops! Page <span style="color: red;">{title}</span> Not Found.'
        } )
    content = matcher.convert_markdown ( file )
    # return entry page
    return render ( request, "encyclopedia/entry.html", {
        "title": title,
        "content": content
    } )


def random_page(request):
    all_page = util.list_entries ()
    rand_page = all_page[random.randint ( 0, len ( all_page ) - 1 )]
    return HttpResponseRedirect ( reverse ( 'encyclopedia:entry', kwargs={
        "title": rand_page
    } ) )


def search_page(request):
    text = request.GET.get ( 'q' ).strip ()
    all_page = util.list_entries ()
    if text in all_page:
        return HttpResponseRedirect ( reverse ( 'encyclopedia:entry', kwargs={
            "title": text
        } ) )
    entries = list ( filter ( lambda l: text in l, all_page ) )
    return render ( request, "encyclopedia/search.html", {
        "entries": entries,
        "count": len ( entries )
    } )


def create_page(request):
    if request.method == "POST":
        form = NewPage ( request.POST )
        print ( form.is_valid () )
        if not form.is_valid ():
            return render ( request, "encyclopedia/error.html", {
                "status": status.HTTP_403_FORBIDDEN,
                "error_msg": "Invalid content."
            } )
        title = form.cleaned_data['title']
        content = form.cleaned_data['content']
        if title in util.list_entries ():
            new_form = NewPage()
            new_form.set_default_value(title, content)
            return render ( request, "encyclopedia/edit_page.html", {
                "form": new_form,
                "error_msg": "Duplicate title.",
            } )
        util.save_entry ( title, content )
        return HttpResponseRedirect ( reverse ( 'encyclopedia:entry', kwargs={
            "title": title
        } ) )
    return render ( request, "encyclopedia/edit_page.html", {
        "form": NewPage ()
    } )


def update_page(request):
    if request.method == "POST":
        title = request.POST.get ( 'title' )
        content = request.POST.get ( 'content' )
        print (content)
        if not title or not content:
            return render ( request, "encyclopedia/error.html", {
                "status": status.HTTP_500_INTERNAL_SERVER_ERROR,
                "error_msg": f'Oops! Update entry page error!.'
            } )
        util.save_entry ( title, content )
        return HttpResponseRedirect ( reverse ( 'encyclopedia:entry', kwargs={
            "title": title
        } ) )
    get_title = request.GET.get ( 'title' )
    page_form = util.get_entry ( get_title )
    return render ( request, "encyclopedia/update_page.html", {
        "title": get_title,
        "content": page_form
    } )

CS50WEB/pset1/wiki/encyclopedia/templates/encyclopedia/edit_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    New Page
{% endblock %}

{% block body %}
        <form class="col-8 needs-validation" novalidate action="{% url 'encyclopedia:create' %}" method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="title" class="form-label">Title</label>
            {{ form.title }}
            <div class="valid-feedback">Looks good!</div>
            <div class="invalid-feedback">Invalid title.</div>
            <span style="color: red;font-size: 80%;" id="errorTitle">{{ error_msg }}</span>
        </div>
        <div class="mb-3">
            {{ form.content }}
            <div class="valid-feedback">Looks good!</div>
            <div class="invalid-feedback">Please write something.</div>
        </div>
        <div class="mb-3">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>
    <script>
        (function () {
          'use strict'
          var forms = document.querySelectorAll('.needs-validation')
          var span = document.querySelector('#errorTitle')
          if (span.innerHTML.length > 0) {
            let title = document.querySelector('#id_title')
            title.value = ""
          }

          Array.prototype.slice.call(forms)
            .forEach(function (form) {
              form.addEventListener('submit', function (event) {
                if (!form.checkValidity()) {
                  event.preventDefault()
                  event.stopPropagation()
                }
                document.querySelector('#errorTitle').style.display = 'none'
                form.classList.add('was-validated')
              }, false)
            })
        })()
    </script>
{% endblock %}

CS50WEB/pset1/wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <div class="container">
        {{ content|safe }}
        <hr>
        <form action="{% url 'encyclopedia:update' %}" method="get">
            {% csrf_token %}
            <input type="hidden" name="title" value="{{ title }}">
            <button class="btn btn-primary">Edit</button>
        </form>
    </div>
{% endblock %}

CS50WEB/pset1/wiki/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Error!
{% endblock %}

{% block style %}
    h1 {
    text-align: center;
    }
{% endblock %}

{% block body %}
    <h1 style="font-size: 90px;">{{ status }}</h1>
    <h1>{{ error_msg|safe }}</h1>
{% endblock %}

CS50WEB/pset1/wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li>
                <a href="{% url 'encyclopedia:entry' title=entry %}">{{ entry }}</a>
            </li>
        {% empty %}
            <li>No entries</li>
        {% endfor %}
    </ul>

{% endblock %}

CS50WEB/pset1/wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
        <style>{% block style %}{% endblock %}</style>
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="get">
                    <input class="search" type="text" name="q" required="required" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random_page' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

CS50WEB/pset1/wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search
{% endblock %}

{% block body %}
    <h1>{{ count }} results found</h1>
    <ul>
        {% for entry in entries %}
            <li>
                <a href="{% url 'encyclopedia:entry' title=entry %}">{{ entry }}</a>
            </li>
        {% empty %}
            <li>No results found</li>
        {% endfor %}
    </ul>
{% endblock %}

CS50WEB/pset1/wiki/encyclopedia/templates/encyclopedia/update_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Update Page
{% endblock %}

{% block body %}
    <form class="col-8 needs-validation" novalidate action="{% url 'encyclopedia:update' %}" method="post">
        {% csrf_token %}
        <h1>{{ title }}</h1>
        <input type="hidden" name="title" value="{{ title }}">
        <hr>
        <div class="mb-3">
            <textarea cols="40" rows="13" name="content" class="form-control">{{ content }}</textarea>
            <div class="valid-feedback">Looks good!</div>
            <div class="invalid-feedback">Please write something.</div>
        </div>
        <div class="mb-3">
            <button type="submit" class="btn btn-primary">Update</button>
        </div>
    </form>
    <script>
        (function () {
          'use strict'
          var forms = document.querySelectorAll('.needs-validation')

          Array.prototype.slice.call(forms)
            .forEach(function (form) {
              form.addEventListener('submit', function (event) {
                if (!form.checkValidity()) {
                  event.preventDefault()
                  event.stopPropagation()
                }
                document.querySelector('#errorTitle').style.display = 'none'
                form.classList.add('was-validated')
              }, false)
            })
        })()
    </script>
{% endblock %}